### ISSUE TITLE
Please clarify licence terms and add LICENCE to the repo

### ISSUE THREAD

**Issue by cepera-ang** [antorsae/sp-society-camera-model-identification#2]
Hi @antorsae! Thank you very much for the sharing of great code for this competition. Could you please provide licence to the code? Absent licence basically means no one could use or copy your code, just read it and get inspiration. I'd suggest on of more permissive ones, like MIT or BSD, if you don't mind wide sharing and adoption :) 
Thanks!

**Comment by antorsae** [comment]
Done, went with GPLv3 for the spirit of sharing if using this code.
