### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by MinuteswithMetrics** [antorsae/sp-society-camera-model-identification#6]
I received the following error: train.py: error: unrecognized arguments: -s 1

What is -s 1?

**Comment by antorsae** [comment]
Apparently it's an argument you've invoked it with which is not there (anymore). Just remove it from command line.

**Comment by MinuteswithMetrics** [comment]
I also received the following error as well:

Traceback (most recent call last):
  File "train.py", line 591, in <module>
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/site-packages/keras/legacy/interfaces.py",
line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/training.py",
line 1735, in fit_generator
    raise ValueError('When using a generator for validation data, '
ValueError: When using a generator for validation data, you must specify a
value for `validation_steps`.

**Comment by antorsae** [comment]
Is the validation data downloaded properly?

**Comment by MinuteswithMetrics** [comment]
I believe it was my folder tree causing the error. I updated the train.py
with my directory. So far it hasn't errored out.

**Comment by MinuteswithMetrics** [comment]
I believe the data is downloaded properly. I am getting the same error.
